### PR TITLE
Clear board

### PR DESCRIPTION
**Pull request by Monchkrit**
This includes changes to the games view to include a show action which currently has a game board showing at game_id = 1 on my implementation. After merging this pull request you need to manually add a game through the rails console to see it working. Otherwise there is no game to show. The path to the view should be http://localhost:3030/games/1 . This also clears all the boards related errors from rspec testing.

### CODE REVIEW

**Comment by Monchkrit** [comment]
Without a solid login page to making the games#show work is tricky. I think once that login is set up and the session is solid all the current issues will resolve.

**Review by KazimieraLuce — COMMENTED** [review]
My only concern with this would be that you have `x_position` and `y_position` in the piece model. From my understanding of the schema, we are using `x_space` and `y_space`. So to be consistent, would it be safer to change the model to the schema set up? What do you think?

**Comment by Monchkrit** [comment]
I don't see what you're referring to. I had something laying around from trying to change the x_space to a string earlier, but it looks like the migration is gone from the current pull request.

**Review by ZoeBKramer — COMMENTED** [review]
Really confused why all the files were deleted and then re-added.

**Comment by Monchkrit** [comment]
Iterative changes are really messy on this platform.

**Comment by ZoeBKramer** [comment]
> Iterative changes are really messy on this platform.

I don't know what you mean by iterative changes, there are over 100 files changed (including the gitignore which shouldn't be touched). When submitting a PR, you should only be submitting file changes which is relevant to it. As this PR stands, I am unable to accept it for a couple reasons: it's impossible to read and review 100+ file changes and know which file change is relevant. And, it seems like you have other people's commits in here.

**Comment by Monchkrit** [comment]
Okay.

**Pull request closed without merging**
