### PR TITLE
Fix board

### PR DESCRIPTION
**Pull request by Monchkrit**
This thing makes a lot of changes, granted. It does what it needs to do though. I'll leave this one hanging out.

Thanks,

### CODE REVIEW

**Review by KazimieraLuce — COMMENTED** [review]
I agree with Zoe's previous comments. I don't understand why all those files have to be changed. Can you unstage those changes Or it is likely simpler to make a new branch with just the `games/show.html.erb` file that you updated and put a PR on that.

**Comment by ZoeBKramer** [comment]
> I agree with Zoe's previous comments. I don't understand why all those files have to be changed. Can you unstage those changes Or it is likely simpler to make a new branch with just the `games/show.html.erb` file that you updated and put a PR on that.

I think this would be the easiest solution

**Comment by Monchkrit** [comment]
Perhaps it's because I'm using Code VS? I don't know. I looked through a bunch of them and there aren't any changes to the files that I can see.

**Comment by ZoeBKramer** [comment]
> Perhaps it's because I'm using Code VS? I don't know. I looked through a bunch of them and there aren't any changes to the files that I can see.

Screenshot (42)
These are all the changes that I see on my end.

**Comment by KazimieraLuce** [comment]
> > Perhaps it's because I'm using Code VS? I don't know. I looked through a bunch of them and there aren't any changes to the files that I can see.
> 
> Screenshot (42)
> These are all the changes that I see on my end.

Yes, I'm seeing the same thing Zoe is. Maybe run `git status` or just start a whole new branch, do a pull from master and just change the `game/show.html.erb` file?

**Pull request closed without merging**
